image: python:3.8

stages:
  - install
  - lint

before_script:
  - echo -e "machine gitlab.kcell.kz\nlogin $DEPLOY_TOKEN_USER\npassword $DEPLOY_TOKEN_PASS" > ~/.netrc
  - chmod 600 ~/.netrc
  - pip install poetry

install-deps:
  stage: install
  script:
    - poetry install

lint:
  stage: lint
  script:
    - poetry run flake8
