image: python:3.8.13-slim-buster

stages:
  - lint

before_script:
  - apt-get update && apt-get install -y git
  - echo -e "machine gitlab.kcell.kz\nlogin $DEPLOY_TOKEN_USER\npassword $DEPLOY_TOKEN_PASS" > ~/.netrc
  - chmod 600 ~/.netrc
  - pip install poetry
  - poetry install

lint:
  stage: lint
  script:
    - poetry run flake8
