repos:
  - repo: local
    hooks:
      - id: format-black
        name: Run black on staged files
        entry: |
          bash -c '
            set -e
            git diff --cached --name-only --diff-filter=ACM | grep "\.py$" | xargs -r poetry run black
            git diff --name-only --diff-filter=M | grep "\.py$" | xargs -r git add
          '
        language: system
        pass_filenames: false

      - id: format-isort
        name: Run isort on staged files
        entry: |
          bash -c '
            set -e
            git diff --cached --name-only --diff-filter=ACM | grep "\.py$" | xargs -r poetry run isort
            git diff --name-only --diff-filter=M | grep "\.py$" | xargs -r git add
          '
        language: system
        pass_filenames: false

      - id: lint-flake8
        name: Run linter on staged files
        entry: |
          bash -c '
            set -e
            git diff --cached --name-only --diff-filter=ACM | grep "\.py$" | xargs -r poetry run flake8 || (
              echo "❌ Linter did not pass. Commit rejected.";
              exit 1
            )
          '
        language: system
        pass_filenames: false