# Generated by Django 4.2.8 on 2025-02-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_count', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitesByVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('site_count', models.IntegerField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites_count.technology')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites_count.vendor')),
            ],
            options={
                'unique_together': {('created_at', 'vendor', 'technology')},
            },
        ),
    ]
