# Generated by Django 4.2.8 on 2025-02-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_count', '0002_vendor_sitesbyvendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sitesbyoperator',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.operator'),
        ),
        migrations.AlterField(
            model_name='sitesbyoperator',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.technology'),
        ),
        migrations.AlterField(
            model_name='sitesbyvendor',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.technology'),
        ),
        migrations.AlterField(
            model_name='sitesbyvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.vendor'),
        ),
        migrations.CreateModel(
            name='SitesByRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('site_count', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.region')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.technology')),
            ],
            options={
                'unique_together': {('created_at', 'region', 'technology')},
            },
        ),
    ]
