# Generated by Django 4.2.8 on 2025-02-25 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_count', '0003_region_alter_sitesbyoperator_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitesByOperatorAndRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('site_count', models.PositiveIntegerField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.operator')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.region')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_count.technology')),
            ],
            options={
                'unique_together': {('created_at', 'operator', 'region', 'technology')},
            },
        ),
    ]
