# Generated by Django 4.2.8 on 2025-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tr_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="radioequipmentclockreference",
            name="unique_radio_equipment_clock_reference",
        ),
        migrations.AddIndex(
            model_name="radioequipmentclockreference",
            index=models.Index(
                fields=["enm", "node_id", "radio_equipment_clock_reference_id"],
                name="tr_data_rad_enm_6b6a84_idx",
            ),
        ),
    ]
